// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using blastd_server.DAL;

namespace Blastd_server.Migrations
{
    [DbContext(typeof(BlastdContext))]
    partial class BlastdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("blastd.Models.SponsorRelationship", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountableID");

                    b.Property<int?>("SponsorID");

                    b.HasKey("ID");

                    b.HasIndex("AccountableID");

                    b.HasIndex("SponsorID");

                    b.ToTable("SponsorRelationship");
                });

            modelBuilder.Entity("blastd.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("blastd.Models.SponsorRelationship", b =>
                {
                    b.HasOne("blastd.Models.User", "Accountable")
                        .WithMany("Sponsors")
                        .HasForeignKey("AccountableID");

                    b.HasOne("blastd.Models.User", "Sponsor")
                        .WithMany("Reports")
                        .HasForeignKey("SponsorID");
                });
#pragma warning restore 612, 618
        }
    }
}
